#!/usr/bin/env python3
"""Render the README's download button to docs/download.svg.

The same button Tama's README uses, in Kibo's palette: a dark panel with the mascot on the left
and "Download Kibo.dmg" beside it. It is dark on both GitHub themes on purpose — GitHub renders
an SVG inside <img>, so the button cannot follow the page's theme, and a dark card holds up on
either ground.

The ghost is drawn from the grid in `Sources/Kibo/KiboSprite.swift` — parsed, not copied, the
same way `make-ghost-gif.py` does it — at a whole-number multiple so every sprite pixel is a
crisp rectangle. The eyes are holes: those cells are simply not drawn, and the panel shows
through, which is how the sprite is built everywhere else.

Colours come from `Theme.swift`'s dark palette by name: panel, dim, text, and the mascot's pale.

    python3 Tools/make-download-button.py    # → docs/download.svg
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPRITE = ROOT / "Sources" / "Kibo" / "KiboSprite.swift"
OUT = ROOT / "docs" / "download.svg"

# Theme.swift, dark side.
PANEL = "#1C1A17"
STROKE = "#9A8F84"   # dim — the same stroke Tama's button uses; the two are siblings
TEXT = "#EDE6DC"
DIM = "#9A8F84"
KIBO = "#F2EEE6"     # Palette.kibo on dark: the ghost is always the opposite of its ground

WIDTH, HEIGHT = 290, 60
PIXEL = 2.5          # 16 columns → 40 px, the size Tama's cat is drawn at
ORIGIN = (18, 10)    # left margin, and (HEIGHT − 16·PIXEL) / 2 to centre vertically


def grid() -> list[list[bool]]:
    source = SPRITE.read_text(encoding="utf-8")

    def rows(pattern: str) -> list[str]:
        match = re.search(pattern, source, re.S)
        if not match:
            raise RuntimeError(f"KiboSprite.swift: no match for {pattern!r}")
        return re.findall(r'"([.Y]{16})"', match.group(1))

    dome = rows(r"private static let dome\s*=\s*\[(.*?)\]")
    hem = rows(r"private static let hem\s*=\s*\[(.*?)\]")
    eyes = rows(r"case \.open:\s*return \[(.*?)\]")
    all_rows = dome + eyes + hem
    if len(all_rows) != 16 or any(len(r) != 16 for r in all_rows):
        raise RuntimeError("expected a 16×16 grid")
    return [[c == "Y" for c in row] for row in all_rows]


def ghost_path(cells: list[list[bool]]) -> str:
    """One <path> of axis-aligned squares. Adjacent squares share edges exactly, so the union
    renders as a single silhouette with no hairline seams between pixels."""
    ox, oy = ORIGIN
    parts = []
    for y, row in enumerate(cells):
        for x, on in enumerate(row):
            if on:
                parts.append(f"M{ox + x * PIXEL:g} {oy + y * PIXEL:g}h{PIXEL:g}v{PIXEL:g}h-{PIXEL:g}z")
    return "".join(parts)


def svg() -> str:
    return f"""<svg width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Download Kibo.dmg for macOS 14+">
  <!-- Generated by Tools/make-download-button.py from KiboSprite.swift and Theme.swift. Regenerate, don't edit. -->
  <rect x="1.5" y="1.5" width="{WIDTH - 3}" height="{HEIGHT - 3}" rx="12" fill="{PANEL}" stroke="{STROKE}" stroke-width="2.5"/>
  <path d="{ghost_path(grid())}" fill="{KIBO}" shape-rendering="crispEdges"/>
  <text x="72" y="29" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif" font-size="17" font-weight="700">
    <tspan fill="{DIM}">Download </tspan><tspan fill="{TEXT}">Kibo.dmg</tspan>
  </text>
  <text x="72.5" y="45" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="10.5" fill="{DIM}" letter-spacing="0.4">macOS 14+ · menu-bar app</text>
</svg>
"""


def main() -> None:
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(svg(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  {OUT.stat().st_size} bytes")


if __name__ == "__main__":
    main()
